# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flare}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Dwan"]
  s.date = %q{2009-11-03}
  s.default_executable = %q{flare-solr}
  s.description = %q{This needs to get updated}
  s.email = %q{mpdwan@gmail.com}
  s.executables = ["flare-solr"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/flare-solr",
     "flare.gemspec",
     "lib/flare.rb",
     "lib/flare/active_record.rb",
     "lib/flare/collection.rb",
     "lib/flare/configuration.rb",
     "lib/flare/index_builder.rb",
     "lib/flare/session.rb",
     "lib/flare/tasks.rb",
     "solr/etc/jetty.xml",
     "solr/etc/webdefault.xml",
     "solr/lib/jetty-6.1.3.jar",
     "solr/lib/jetty-util-6.1.3.jar",
     "solr/lib/jsp-2.1/ant-1.6.5.jar",
     "solr/lib/jsp-2.1/core-3.1.1.jar",
     "solr/lib/jsp-2.1/jsp-2.1.jar",
     "solr/lib/jsp-2.1/jsp-api-2.1.jar",
     "solr/lib/servlet-api-2.5-6.1.3.jar",
     "solr/solr/conf/elevate.xml",
     "solr/solr/conf/protwords.txt",
     "solr/solr/conf/schema.xml",
     "solr/solr/conf/solrconfig.xml",
     "solr/solr/conf/stopwords.txt",
     "solr/solr/conf/synonyms.txt",
     "solr/solr/lib/geoapi-nogenerics-2.1-M2.jar",
     "solr/solr/lib/gt2-referencing-2.3.1.jar",
     "solr/solr/lib/jsr108-0.01.jar",
     "solr/solr/lib/locallucene.jar",
     "solr/solr/lib/localsolr.jar",
     "solr/start.jar",
     "solr/webapps/solr.war",
     "test/helper.rb",
     "test/test_flare.rb"
  ]
  s.homepage = %q{http://github.com/michaeldwan/flare}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This needs to get updated}
  s.test_files = [
    "test/helper.rb",
     "test/test_flare.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rsolr>, [">= 0.9.6"])
      s.add_runtime_dependency(%q<escape>, [">= 0.0.4"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<rsolr>, [">= 0.9.6"])
      s.add_dependency(%q<escape>, [">= 0.0.4"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<rsolr>, [">= 0.9.6"])
    s.add_dependency(%q<escape>, [">= 0.0.4"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

